package:
    type:           yii2-extension
    name:           yii2-asset-select2
    title:          Yii2 asset for Select2 plugin
    keywords:       yii2, asset, select2
    namespace:      hiqdev\yii2\assets\select2
    description:    |
        This package is Yii2 asset bundle for [select2](https://github.com/select2/select2) jQuery plugin

